### ISSUE TITLE
This plugin breaks globalias

### ISSUE THREAD

**Issue by Sciencentistguy** [chisui/zsh-nix-shell#31] opened 2022-01-20 21:02 UTC
## Issue description

https://github.com/ohmyzsh/ohmyzsh/tree/master/plugins/globalias is a plugin that exapnds aliases when you press space.

Having this plugin loaded breaks the functionality of that.

Interestingly, when in a nix-shell it starts to work again.

This persists under a home-manager installation on darwin-aarch64, and a manual "just source the plugin file" installation on (arch)linux-x86_64 (and darwin-aarch64).

### Steps to reproduce

1. Install both plugins
2. Observe it not working

## Technical details

Please run the following commands and paste the results:
1. `command nix-shell -p nix-info --run "nix-info -m"`
2. `zsh --version`

1. 
```
 - system: `"aarch64-darwin"`
 - host os: `Darwin 21.2.0, macOS 12.1`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.5.1`
 - channels(jamie): `"darwin, home-manager"`
 - channels(root): `"darwin, home-manager, nixpkgs-22.05pre346058.bc59ba15b64"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixpkgs`
 ```

2. `zsh 5.8 (aarch64-apple-darwin20.1.0)`

**Comment by chisui** [comment] 2022-01-22 15:27
I could not reproduce this issue. Here is my home-manager zsh config:

```
{
  programs.zsh = {
    enable = true;
    enableCompletion = true;
    plugins = with pkgs.nur.repos.chisui.zsh-plugins; [
      zsh-nix-shell
    ];
    oh-my-zsh = {
      enable = true;
      plugins = [ "git" "globalias" ];
    };
  };
}
```

At least `{1..4}` expands to `1 2 3 4`.

How are you installing the `zsh-nix-shell` exactly?

**Comment by Sciencentistguy** [comment] 2022-01-22 15:33
I source the `.plugin.zsh` file from the `.zshrc`, which is exactly what home-manager' generated zshrc does

**Comment by chisui** [comment] 2022-01-22 15:43
Relevant parts of my generated `.zshrc`:

```
path+="$HOME/.zsh/plugins/zsh-nix-shell"
fpath+="$HOME/.zsh/plugins/zsh-nix-shell"

plugins=(git, globalias)
source $ZSH/oh-my-zsh.sh

if [[ -f "$HOME/.zsh/plugins/zsh-nix-shell/nix-shell.plugin.zsh" ]]; then
  source "$HOME/.zsh/plugins/zsh-nix-shell/nix-shell.plugin.zsh"
fi
```

It seems that the plugin is added to `path` and `fpath`, which shouldn't be necessary. Does adding the plugin dir to `path` and/or `fpath` fix your issue?

**Comment by Sciencentistguy** [comment] 2022-01-22 15:49
No it doesn't, unfortunately

**Comment by chisui** [comment] 2022-01-22 15:51
Hm, maybe the order matters? Do you have any other plugins active? Could you post your `.zshrc`?

**Comment by Sciencentistguy** [comment] 2022-01-22 15:59
It's in here: https://github.com/Sciencentistguy/dotfiles

**Comment by chisui** [comment] 2022-01-22 16:03
Does it work move `globalias` below the `zsh-nix-shell` source?

**Comment by Sciencentistguy** [comment] 2022-01-22 16:21
Oh that does fix it thanks!

I wonder why that is?

**Comment by chisui** [comment] 2022-01-22 17:30
`globalias` seems to do some special stuff. I have no idea what. To be honest, I don't plan to support that in this plugin. So if that fixes your issue I'll close this one.

**Closed as completed by chisui** 2022-01-22 17:30 UTC
Labels: bug, MacOS, Linux
